name: Update latest data

on:
#  schedule:
#    - cron: '0 */4 * * *'
#    - cron: '*/5 17 * * *' # Yes, this is very frequent, but GitHub Actions doesn't actually trigger it this often
  workflow_dispatch:

jobs:
  update-latest-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js version from .nvmrc
        id: set-node
        run: echo "::set-output name=node::$(cat .nvmrc)"

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.set-node.outputs.node }}

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install NPM dependencies
        run: npm ci

      - name: Expose ENV as config
        run: echo "module.exports = process.env;" > build/config.js

      - name: Fetch latest emote
        run: npm run build:fetch-emote
        env:
          TWITCH_USERNAME: ${{ secrets.TWITCH_USERNAME }}
          TWITCH_PASSWORD: ${{ secrets.TWITCH_PASSWORD }}
          TWITCH_CHANNEL: ${{ secrets.TWITCH_CHANNEL }}
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}

      - name: Update historical data
        id: update-data
        run: |
          UPDATED=$(npm run --silent build:update-data)
          echo $UPDATED
          echo "::set-output name=updated::$UPDATED"

      - name: Commit and push if updated
        if: ${{ steps.update-data.outputs.updated == 'updated' }}
        run: |
          git status -s
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add build/data.json
          git add build/history.json
          git commit -m "New PogChamp data"
          git push
